Fix test migration for django3 + mysql
The tests (in a third party app) fail with the following errors:

django.db.utils.OperationalError: (1025, "Error on rename of
'./test_phpbb/#sql-423_33' to './test_phpbb/phpbb_topics' (errno: 150)")

mysql> SHOW ENGINE INNODB STATUS

------------------------
LATEST FOREIGN KEY ERROR
------------------------
140817 12:15:02 Error in foreign key constraint of table test_phpbb/phpbb_drafts:
there is no index in referenced table which would contain
the columns as the first columns, or the data types in the
referenced table do not match the ones in table. Constraint:
,
  CONSTRAINT "topic_id_refs_topic_id_2fe0f628" FOREIGN KEY ("topic_id") REFERENCES "phpbb_topics" ("topic_id")
The index in the foreign key in table is "phpbb_drafts_76f18ad3"
See http://dev.mysql.com/doc/refman/5.5/en/innodb-foreign-key-constraints.html
for correct foreign key definition.